### ISSUE TITLE
know when the audio and video mute button is clicked

### ISSUE THREAD

**Issue by ronny141** [AgoraIO-Community/Web-React-UIKit#10]
know when the audio and video mute button is clicked,,

I have tried the following but it doesn't work

callbacks: {
      "local-user-mute-audio": (status) =>  { console.log('status', status) },
    },

thank you

**Comment by EkaanshArora** [comment]
Fixed in v1.0.7, please update.

**Comment by ronny141** [comment]
thank you @EkaanshArora
