### ISSUE TITLE
Invalid App ID

### ISSUE THREAD

**Issue by monizb** [AgoraIO-Community/Web-React-UIKit#11]
I am trying to integrate UI Kit with my app, I generate join token server side and when I try to render the Agora UI Kit, I get the following error : 

`**"'AgoraRTCException', code: 'CAN_NOT_GET_GATEWAY_SERVER', message: 'AgoraRTCError CAN_NOT_GET_GATEWAY_SERVER: invalid vendor key, can not find appid'**`

I thought it was a mistake on my end, I went to the Agora dashboard and clicked on "create web demo link" and it didn't work there as well, the same error was popping up on the console.

P.S: My app ID is correct

**Comment by EkaanshArora** [comment]
When you create a new project in the Agora console, it can sometimes take a few minutes for the appId to be enabled. Can you try again with [agora-react-uikit.vercel.app](https://agora-react-uikit.vercel.app/)?

**Comment by monizb** [comment]
> When you create a new project in the Agora console, it can sometimes take a few minutes for the appId to be enabled. Can you try again with [agora-react-uikit.vercel.app](https://agora-react-uikit.vercel.app/)?

I can confirm that you were right, I just tried it the next day and it worked thanks!
