### ISSUE TITLE
Unable to view local video.

### ISSUE THREAD

**Issue by iamkunall** [AgoraIO-Community/Web-React-UIKit#14]
I try to run the example project and add my app id in /example/src/App.tsx file. I am using the secure token for authentication so i add tokens in rtcProps and give a role as host and channel name which i used to generate the token. Still not able to view my local video. Screens show just blank

**Comment by EkaanshArora** [comment]
Do you see any errors in the browser console?

**Comment by iamkunall** [comment]
Hi, @EkaanshArora thanks for the response not getting any errors in the console.

**Comment by iamkunall** [comment]
Hi, @EkaanshArora thanks it's fixed now. It's an issue with auth token generated by my backend code.
