### ISSUE TITLE
Is it somehow possible to disable the video and just use the audio?

### ISSUE THREAD

**Issue by esoinila** [AgoraIO-Community/Web-React-UIKit#19]
Feature request:
I know the name of the component is VideoUIKit, but I would really like a switch to start everybody without video (and keep them that way). I only need the audio and, I really like the code here, so is there a start-up-props etc. option to do this. If not then this is my feature request.

**Comment by Mihai-github** [comment]
Hi, I'm having the same issue using the UIKIt even though I have a supposed option that says:

/**
* Enable the mic before joining the call. (default: true)
*/
enableAudio?: boolean;
 /**
* Enable the camera before joining the call. Only use for initiak(default: true)
*/
enableVideo?: boolean;

For some reason does nothing ... did anyone figure out another solution?

**Comment by EkaanshArora** [comment]
Hi sorry about the late response, this a placeholders prop to add this functionality in the future  but it isn’t part of the UIKit as of now - I’ll update the issue once we’ve added this.

**Comment by Mihai-github** [comment]
Hi @EkaanshArora ,

    Do you have an ideea when this will be available since now for the project I'm working on is needed and also was requested by the clients... so you can expect that would help me to know when will be available 


Thanks

**Comment by EkaanshArora** [comment]
I'd be happy to review a PR if you want to take up this feature, but this will take some time for me to get to it
