### ISSUE TITLE
Gatsby - error "window" is not available during server side rendering.

### ISSUE THREAD

**Issue by gdSuhail** [AgoraIO-Community/Web-React-UIKit#2]
Hi @EkaanshArora,
Thanks for the UiKit. 

I have added the UIKit to one of our Gatsby project and it is working great but the problem  is occuring during the build process. I am getting the `error "window" is not available during server side rendering.` error during running the build. The error is coming in the `AgoraRTC_N-production.js` file. I tried checking the condition of `isBrowser()` and then rendering the `AgoraUIKit` but still the same error is occuring. Please tell me how can I fix this issue. Thanks

![image](https://user-images.githubusercontent.com/79185627/153613174-be3517cc-be07-477c-9259-b1ff32c50d70.png)

**Comment by EkaanshArora** [comment]
Are you also handling the UIKit `import`using the `isBrowser()` check?

**Comment by gdSuhail** [comment]
> Are you also handling the UIKit `import`using the `isBrowser()` check?

Thanks for reply.
No, I am importing it directly and checking the condition before rendering.

edit: 
I tried importing(require) based on the condition and it fixed the issue.

Thanks for the help.
