### ISSUE TITLE
Not working on production build of next js

### ISSUE THREAD

**Issue by aniksharif** [AgoraIO-Community/Web-React-UIKit#20]
Hi I am using this library with Next js. It's working fine in development mode. But in production mode it's not working not even showing!

**Comment by EkaanshArora** [comment]
Can you share logs? Here's a repo using the UIKit with Next: https://github.com/EkaanshArora/Agora-FullStack-Nextjs

**Comment by EkaanshArora** [comment]
feel free to reopen if the issue persists

**Comment by aniksharif** [comment]
@EkaanshArora Thank you for your response. I am sorry that I forgot to respond. The issue was I was using `swcMinify` true in the config which was making this issue. After removing it, it worked!
