### ISSUE TITLE
enableVideo: false or enableAudio: false not working for LocalParticipant

### ISSUE THREAD

**Issue by Mihai-github** [AgoraIO-Community/Web-React-UIKit#21]
Hi,

    I have the following configuration and seems to not work for the LocalParticipant even though i set the camera and mic to false.

`
const [rtcProps, setRTCProps] = React.useState<RtcPropsInterface>({
		CustomVideoPlaceholder: Placeholder,
		appId: "c532a7b1c4e04ad3a35052133adafaa6",
		channel: "",
		token: "",
		activeSpeaker: true,
		enableAudio: queryParams["audio"] === "on" ? true : false,
		enableVideo: queryParams["video"] === "on" ? true : false,
		role: "host",
		uid: authUserId as number,
		layout: layout.grid,
		disableRtm: true,
});
`

Any idea why this is not working???

**Comment by EkaanshArora** [comment]
Hi sorry about the late response, this a placeholder prop to add this functionality in the future but it isn’t part of the UIKit as of now - I’ll update the issue once we’ve added this. #19
