### ISSUE TITLE
[QUESTION] having a listener or callback when a call is started propertly

### ISSUE THREAD

**Issue by elenitaex5** [AgoraIO-Community/Web-React-UIKit#26]
Hi! I'm been researching in code and documentation but I have a doubt about it. There's a listener or a callback we could include for when a call is propertly initialized (with no errors)? We need to track and log the moment of starting a video call but I'm not sure if there's something we can use in UI Kit

**Comment by EkaanshArora** [comment]
You can listen to [connection-state-change](https://api-ref.agora.io/en/video-sdk/web/4.x/interfaces/iagorartcclient.html#event_connection_state_change), when the current state is `"CONNECTED"` it means the channel is joined successfully.

**Comment by elenitaex5** [comment]
THANKS
