### ISSUE TITLE
As an audience user, mute the remote host

### ISSUE THREAD

**Issue by jalamprea** [AgoraIO-Community/Web-React-UIKit#30]
Is it possible to mute/unmute the remote host while I'm joined as an audience user?

**Comment by EkaanshArora** [comment]
I think this will work. Have you faced an issue doing this?

**Comment by jalamprea** [comment]
When I set the role as **audience**, on the toolbar, I only can view a button to end the call, but there are no options to mute the remote video from the host.
Is there any specific config or something we need to add to the props?

**Comment by EkaanshArora** [comment]
Are you using the UIKit for both the host and the audience clients? 
<img width="1241" alt="Screenshot 2023-02-01 at 2 17 13 PM" src="https://user-images.githubusercontent.com/10047883/215994419-1b35caaa-1478-46bd-b9fd-d4152a6252ff.png">
If you hover over the remote host, you should be able to see the mute icons on the top left of their tile
