### ISSUE TITLE
How do you listen for when new user join the channel?

### ISSUE THREAD

**Issue by BMTCompany2** [AgoraIO-Community/Web-React-UIKit#31]
I would like to start recording the call when at least two users have joined the channel.  How do I listen for when new users join the channel?

**Comment by BMTCompany2** [comment]
Additionally, how can you change the control buttons and background colors?  I saw how stuff can be customized in the Flutter Uikit but haven't seen anything for React.

**Comment by marutifh** [comment]
> I would like to start recording the call when at least two users have joined the channel. How do I listen for when new users join the channel?

Did you get any response or identify the solution?
@EkaanshArora

**Comment by BMTCompany2** [comment]
I ended up figuring it out.  This works for me
`              <AgoraUIKit
                rtcProps={{
                  appId: process.env.REACT_APP_AGORA_APP_ID,
                  channel: channelName,
                  token: rtcToken, // add your token if using app in secured mode
                  role,
                  uid,
                  layout: layout.grid,
                  setVideoEncoder:
                    {
                      width: 1280,
                      height: 720,
                    },
                }}
                styleProps={{
                  localBtnContainer: { backgroundColor: '#424242' },
                }}
                // rtmProps={{ username: clientFullName, displayUsername: true }}
                callbacks={{
                  EndCall: () => endCallCleanup(),
                  'user-joined': () => startRecording(),
                }}
              />`
![image](https://user-images.githubusercontent.com/96481893/228272309-5816b197-ea38-4a05-9548-23dfcd5af9b5.png)

You can see in the callbacks 'user-joined'.  This has worked for me to catch when new people join the call.

**Comment by Aoun2686** [comment]
any idea how to turn off camera when user leaves? my camera light remains on until i dont refresh the page. also, how can i pass initial settings for audio and video? i have a preparing screen where user choses to turn their camera on or off and for mic as well. i need to reflect those settings in video call.
