### ISSUE TITLE
Which JS bundle your referring to?

### ISSUE THREAD

**Issue by NMamkegh** [AgoraIO-Community/Web-React-UIKit#36]
can you explain which JS bundle you are referring to? in how to use #2

**Comment by NMamkegh** [comment]
this component cant be built, it keep giving errors at build

**Comment by nfmshow** [comment]
@NMamkegh If you experienced problems building the web component for a non react project, you can try using this [library](https://github.com/nfmshow/agora-ui-kit) as an alternative.
Disclaimer: I am the author.
