### ISSUE TITLE
camera light remain on when user leaves video call and how to use pre call settings in video call

### ISSUE THREAD

**Issue by Aoun2686** [AgoraIO-Community/Web-React-UIKit#37]
any idea how to turn off camera when user leaves? my camera light remains on until i dont refresh the page. also, how can i pass initial settings for audio and video? i have a preparing screen where user choses to turn their camera on or off and for mic as well. i need to reflect those settings in video call.

**Comment by MetaSeth** [comment]
Apparently it's because of React.StrictMode who open 2 instance.
And when leaving only one is left ...
