### ISSUE TITLE
to use back camera and front camera switch functionality using Agora RTC SDK ng 

### ISSUE THREAD

**Issue by vip2805love** [AgoraIO-Community/Web-React-UIKit#38]
hey, I want to implement switching camera functionality for live streaming in my project. as of now, the front camera is used as the default camera. but in the case of the mobile browser, I want to utilize the change camera functionality so the user can change the camera accordingly.
please provide me with some solution for this

**Comment by simo-an** [comment]
This function has been scheduled at 4.19.0 and will be published soon.
At that version you can pass facingMode into setDevice method
