### ISSUE TITLE
screen share

### ISSUE THREAD

**Issue by NMamkegh** [AgoraIO-Community/Web-React-UIKit#39]
it was working fine earlier, then suddenly it stopped working
anyone aware of any recent changes Agora did? or is it chrome?

**Comment by harshw-aumhum** [comment]
Screen sharing not working. Could you solve this?

**Comment by harsh-wadhwa** [comment]
you are right. I have been trying to implement screen sharing and it is not working.
I am passing enableScreensharing: true in rtcProps and there is the screensharing button in UI > clicking it asks for what to share in the chrome's submenu of sharing screen which asks tab or entire screen etc.
But after that step, I don't see any screen shared on other person's side or on my side UI.

**Comment by EkaanshArora** [comment]
tracking in #40
