### ISSUE TITLE
Error Code 102 - Logout failure. The client has already been logged out.

### ISSUE THREAD

**Issue by anwarhossain1** [AgoraIO-Community/Web-React-UIKit#43]
I made a custom component and I use it in my 2 user side. But getting this error. 

My code block is,

`
import {IAgoraCredentials} from '@/pages/lawyer/video-call';
import {Button} from '@mui/material';
import AgoraUIKit from 'agora-react-uikit';
import {useState} from 'react';
const VideoWithUIKit = ({credentials}: {credentials: IAgoraCredentials}) => {
  const [videoCall, setVideoCall] = useState(false);
  const rtcProps = {
    appId: credentials?.APP_ID,
    channel: credentials?.CHANNEL, // your agora channel
    token: credentials?.TOKEN, // use null or skip if using app in testing mode
  };
  const callbacks = {
    EndCall: () => setVideoCall(false),
  };
  return videoCall ? (
    <div style={{display: 'flex', width: '100vw', height: '100vh'}}>
      <AgoraUIKit rtcProps={rtcProps} callbacks={callbacks} />
    </div>
  ) : (
    <Button onClick={() => setVideoCall(true)}>Start Call</Button>
  );
};

export default VideoWithUIKit;

`

Also when i leave the call by using the leave button provides by the ui kit, it gives another error,

`Unhandled Runtime Error

RtmInvalidStatusError:  Error Code 102 - Logout failure. The client has already been logged out.`

**Comment by AdeelCyber** [comment]
I'm facing the same issue, did you find any solution?
