### ISSUE TITLE
When users attempt to share their screen, only a black screen is displayed for the recipient 

### ISSUE THREAD

**Issue by hiftikha** [AgoraIO-Community/Web-React-UIKit#60]
1. Problem description:
   - When users attempt to share their screen, only a black screen is displayed for the recipient 
   - This issue is preventing us from conducting a planned session on our platform.

2. Technical details:
   - We are using Agora UI Kit, which has dependencies on older versions of Agora libraries:
     - agora-rtc-react: ^1.1.3
     - agora-rtm-react: ^1.1.2
   - The latest version of agora-rtc-react is 2.2.0 (updated 15 days ago), but our UI Kit is locked to an older version.

3. Attempted solutions:
   - We have tried various troubleshooting steps but have been unable to resolve the issue.

4. Urgency:
   - This is an urgent matter as we have a scheduled session that requires screen sharing functionality.

5. Request for assistance:
   - We need immediate support to fix the screen sharing functionality with our current setup
     
![Screenshot 2024-07-02 at 12 13 54 PM](https://github.com/AgoraIO-Community/VideoUIKit-Web-React/assets/22324937/0deed7ea-36f7-4a31-8b4f-57e81c271a14)
![Screenshot 2024-07-02 at 12 13 42 PM](https://github.com/AgoraIO-Community/VideoUIKit-Web-React/assets/22324937/6a024303-46f5-4f12-8115-4db8fecb9fb8)

The following is how we're embedding the UIKit
```
<AgoraUIKit
              rtcProps={{
                appId: `${agoraAppId}`,
                channel: session.id,
                token: null,
                layout: layout.grid,
                enableScreensharing: true 
              }}
              rtmProps={{ username: `${username}_host_${isHost}` || 'user', displayUsername: true }}
              callbacks={{
                EndCall: () => {
                  setVideocall(false)
                  onClose()
                },
              }} /></>
              ```

**Comment by digitallysavvy** [comment]
Thanks for reaching out @hiftikha, I am currently working on upgrading the build to the latest versions of the React JS SDK. 

Please test using the [updateToV2.1](https://github.com/AgoraIO-Community/VideoUIKit-Web-React/tree/updateToV2.1) branch. This should resolve screen sharing issues. 

```bash
nom install AgoraIO-Community/VideoUIKit-Web-React/#updateToV2.1
```

**Comment by hiftikha** [comment]
I am unable to resolve the screen sharing issues after updating to that branch. 
`npm install AgoraIO-Community/VideoUIKit-Web-React#updateToV2.1`

**Comment by morcena09** [comment]
Hi @hiftikha ,

We have identified that your issue is not related to the React UIKit and is currently involving [Agora AppBuilder](https://appbuilder.agora.io/). Any solutions using the UIKit will not work in your current project. Therefore, we kindly suggest reaching out to Agora [technical support](https://agora-ticket.agora.io/) for more details.


Thank you.
