### ISSUE TITLE
Changes in Wiki

### ISSUE THREAD

**Issue by BearTS** [AgoraIO-Community/Web-React-UIKit#7]
So , in the wiki 
![image](https://user-images.githubusercontent.com/65192718/162031755-83187fb4-b6bf-46ba-9dfa-0bfb430e1117.png)
There is an extra div closing tag under the example section 
Along with that, on 6th line of the same code snippet, SetRole is not defined (can be replaced with setHost perhaps)

**Comment by EkaanshArora** [comment]
Thanks, fixed!
