### ISSUE TITLE
How to add a new component to LocalControls?

### ISSUE THREAD

**Issue by gdSuhail** [AgoraIO-Community/Web-React-UIKit#9]
I want to add a new new component to LocalControls, I checked the repo but I didn't find any solution. Can you plz tell me how to do that? I want to add a timer and few other buttons as follows:

![image](https://user-images.githubusercontent.com/79185627/162756093-2684165d-f673-4a7f-a408-3fb86a4bddbb.png)

**Comment by EkaanshArora** [comment]
You can go through [this repo](https://github.com/EkaanshArora/Agora-Web-UIKit-RTMP/) to see how you can use the modular components from the UIKit to add a custom button.
[Here](https://levelup.gitconnected.com/streaming-videos-in-your-livestream-using-the-agora-cloud-player-179199301eec) is an in depth blog as well.

**Comment by gdSuhail** [comment]
> You can go through [this repo](https://github.com/EkaanshArora/Agora-Web-UIKit-RTMP/) to see how you can use the modular components from the UIKit to add a custom button. [Here](https://levelup.gitconnected.com/streaming-videos-in-your-livestream-using-the-agora-cloud-player-179199301eec) is an in depth blog as well.

Thank you, I'll check it.
